/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiPublicHooksDailyPredictionsRouteImport } from './routes/api/public/hooks/daily-predictions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyPredictionsRoute =
  ApiPublicHooksDailyPredictionsRouteImport.update({
    id: '/api/public/hooks/daily-predictions',
    path: '/api/public/hooks/daily-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/predictions': typeof PredictionsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/hooks/daily-predictions': typeof ApiPublicHooksDailyPredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/predictions': typeof PredictionsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/hooks/daily-predictions': typeof ApiPublicHooksDailyPredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/predictions': typeof PredictionsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/hooks/daily-predictions': typeof ApiPublicHooksDailyPredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/predictions'
    | '/match/$matchId'
    | '/api/public/hooks/daily-predictions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/predictions'
    | '/match/$matchId'
    | '/api/public/hooks/daily-predictions'
  id:
    | '__root__'
    | '/'
    | '/predictions'
    | '/match/$matchId'
    | '/api/public/hooks/daily-predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PredictionsRoute: typeof PredictionsRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  ApiPublicHooksDailyPredictionsRoute: typeof ApiPublicHooksDailyPredictionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-predictions': {
      id: '/api/public/hooks/daily-predictions'
      path: '/api/public/hooks/daily-predictions'
      fullPath: '/api/public/hooks/daily-predictions'
      preLoaderRoute: typeof ApiPublicHooksDailyPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PredictionsRoute: PredictionsRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  ApiPublicHooksDailyPredictionsRoute: ApiPublicHooksDailyPredictionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
